### ISSUE TITLE
Alternative CSS selector

### ISSUE THREAD

**Issue by jim-rosales** [Craft4Coffee/colmaracademy#4]
Just to pose a different way of doing things for both of these rules you could have omitted the first class and just applied the desired CSS using the ids for both the targeted elements.

For example
```CSS
#name1 {
  font-weight: 700;
  color: #000;
}


#name2 {
  color: #cc0033;
  font-weight: 500;
}

#name1, #name2 {
    text-transform: uppercase;
}
```

https://github.com/Craft4Coffee/colmaracademy/blob/f85b56a0535355f072eb964d81b1b7d0a4f04751/resources/css/style.css#L53-L63
